[book]
authors = ["c0utin"]
language = "en"
multilingual = false
src = "src"
title = "things"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
